rvm:
  - ree
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/rails_2.gemfile
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_2.gemfile
    - rvm: ree
      gemfile: gemfiles/rails_4.gemfile
bundler_args: ""
script: bundle exec rake test
